"""add review_body to model

Revision ID: 5384a532f1cc
Revises: bf88e436aacd
Create Date: 2023-08-27 13:24:26.695896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5384a532f1cc'
down_revision: Union[str, None] = 'bf88e436aacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_body', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'review_body')
    # ### end Alembic commands ###
